#
installer-language=en
prefix=/opt/bitnami
#
mode=unattended
unattendedmodeui=none
#
base_user=bitnami
base_user_name=${wp_user}
base_mail=${wp_user_email}
base_password=${wp_user_pass}
#
wordpress_blog_name=${wp_name}
wordpress_site=${wp_site_url}
#
smtp_enable=0
#
launch_cloud=0
